---
test:
  name: Solidity Transfer
  description: This is a solidity transfer benchmark of FISCO BCOS for caliper
  clients:
    type: local
    number: 1
  rounds:
  - label: addUser
    description: generate users for transfer test later
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1000
    callback: ./addUser.js
  - label: transfer
    description: Test performance of transfer
    txNumber:
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1000
    callback: ./transfer.js